// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example.proto

// Go gRPC Example
//
// This example is used to show how to use gRPC and
// gRPC-Gateway with Go Protobuf.

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *HelloRequest) Validate() error {
	return nil
}
func (this *HelloReply) Validate() error {
	return nil
}
